### ISSUE TITLE
Is Openroast known to work on Mac OS X Yosemite?

### ISSUE THREAD

**Issue by talumbau** [Roastero/Openroast#40]
Hi, this is a great project! I have `freshroastsr700` working on my Mac, but not Openroast.

It looks like the latest supported builds of `qt` on Mac are `pyqt5` and `qt5` for Python 3.4, but this page:

https://github.com/Roastero/openroast/wiki/Setting-Up-A-Development-Environment

seems to suggest using pyqt5 with Python 3.5 on Mac. I get an error message:

```
This application failed to start because it could not find or load the Qt platform plugin "cocoa".
```

when trying to use `Openroast` on Mac OS X Yosemite with a Python 3.4 environment with `pyqt5` and `qt5` installed. So, if someone has it working Yosemite, please let me know how you achieved this result.

**Comment by lodge93** [comment]
Openroast should run on Yosemite, have you tried a packaged release found here: https://github.com/Roastero/Openroast/releases/tag/v1.0.1? I checked the machine used to build that package, it looks like I was using python3.5 and pyqt 5.5.1. Let me know if you get it working, and what the fix was so I can update the documentation.
